name: Setup Node.js Dependencies with Prisma

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  build-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Initialize and install dependencies
        run: |
          npm init -y
          npm i express bcryptjs jsonwebtoken dotenv helmet cors express-rate-limit cookie-parser
          npm i @prisma/client
          npm i -D prisma nodemon
